// DEST: src/test/java/de/burger/forensics/plugin/BtmGenPluginFunctionalTest.java
package de.burger.forensics.plugin;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;
import org.gradle.testkit.runner.BuildTask;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.TaskOutcome;
import org.junit.jupiter.api.Test;

class BtmGenPluginFunctionalTest {

    @Test
    void explicitTaskRegistrationDefaultHeaderHasNoTimestamp() throws IOException {
        File projectDir = Files.createTempDirectory("btmgen-plugin-test1").toFile();
        projectDir.deleteOnExit();
        writeSettings(projectDir);
        writeBuildScript(projectDir, false);
        writeMinimalSource(projectDir);

        var result = GradleRunner.create()
                .withProjectDir(projectDir)
                .withArguments("generateBtmRules", "--stacktrace")
                .withPluginClasspath()
                .build();

        BuildTask task = result.task(":generateBtmRules");
        assertEquals(TaskOutcome.SUCCESS, task == null ? null : task.getOutcome(),
                "generateBtmRules should succeed");

        String output = readFirstOutputFile(projectDir);
        assertTrue(output.lines().findFirst().orElse("")
                        .contains("Generated by de.burger.forensics.btmgen"),
                "Default header should not contain timestamp");
        assertFalse(output.contains("Generated at"),
                "Timestamp should be omitted by default for cacheability");
    }

    @Test
    void explicitTaskRegistrationIncludeTimestampTrueAddsTimestamp() throws IOException {
        File projectDir = Files.createTempDirectory("btmgen-plugin-test2").toFile();
        projectDir.deleteOnExit();
        writeSettings(projectDir);
        writeBuildScript(projectDir, true);
        writeMinimalSource(projectDir);

        var result = GradleRunner.create()
                .withProjectDir(projectDir)
                .withArguments("generateBtmRules", "--stacktrace")
                .withPluginClasspath()
                .build();

        BuildTask task = result.task(":generateBtmRules");
        assertEquals(TaskOutcome.SUCCESS, task == null ? null : task.getOutcome(),
                "generateBtmRules should succeed");

        String output = readFirstOutputFile(projectDir);
        assertTrue(output.lines().findFirst().orElse("").contains("Generated at"),
                "Header should include timestamp when includeTimestamp=true");
    }

    private void writeSettings(File projectDir) throws IOException {
        Files.writeString(new File(projectDir, "settings.gradle.kts").toPath(),
                "rootProject.name = \"sample-project\"\n");
    }

    private void writeBuildScript(File projectDir, boolean includeTimestamp) throws IOException {
        String script = String.join("\n",
                "plugins {",
                "    id(\"de.burger.forensics.btmgen\")",
                "}",
                "",
                "repositories { mavenCentral() }",
                "",
                "// Explicitly register the task; plugin does not auto-create it anymore",
                "tasks.register<de.burger.forensics.plugin.GenerateBtmTask>(\"generateBtmRules\") {",
                "    // Configure explicitly to avoid relying on extension wiring",
                "    srcDirs.set(listOf(\"src/main/kotlin\", \"src/main/java\"))",
                "    packagePrefix.set(\"\")",
                "    helperFqn.set(\"de.burger.forensics.ForensicsHelper\")",
                "    entryExit.set(true)",
                "    trackedVars.set(emptyList())",
                "    includeJava.set(true)",
                "    includeTimestamp.set(" + includeTimestamp + ")",
                "    maxStringLength.set(0)",
                "    pkgPrefixes.set(emptyList())",
                "    includePatterns.set(emptyList())",
                "    excludePatterns.set(emptyList())",
                "    parallelism.set(Runtime.getRuntime().availableProcessors().coerceAtLeast(1))",
                "    shards.set(Runtime.getRuntime().availableProcessors().coerceAtLeast(1))",
                "    gzipOutput.set(false)",
                "    filePrefix.set(\"tracing-\")",
                "    rotateMaxBytesPerFile.set(4L * 1024 * 1024)",
                "    rotateIntervalSeconds.set(0)",
                "    flushThresholdBytes.set(64 * 1024)",
                "    flushIntervalMillis.set(2000)",
                "    writerThreadSafe.set(false)",
                "    minBranchesPerMethod.set(0)",
                "    safeMode.set(false)",
                "    forceHelperForWhitelist.set(false)",
                "    maxFileBytes.set(2_000_000)",
                "    useAstScanner.set(true)",
                "    outputDir.set(layout.buildDirectory.dir(\"forensics\"))",
                "}",
                "");
        Files.writeString(new File(projectDir, "build.gradle.kts").toPath(), script);
    }

    private void writeMinimalSource(File projectDir) throws IOException {
        File sourceDir = new File(projectDir, "src/main/kotlin");
        if (!sourceDir.mkdirs() && !sourceDir.exists()) {
            throw new IOException("Failed to create source directory");
        }
        String source = String.join("\n",
                "fun hello(name: String): String {",
                "    return \"Hello, ${'$'}name\"",
                "}");
        Files.writeString(new File(sourceDir, "TopLevel.kt").toPath(), source);
    }

    private String readFirstOutputFile(File projectDir) throws IOException {
        File outputDir = new File(projectDir, "build/forensics");
        File[] files = outputDir.listFiles((dir, name) -> name.startsWith("tracing-") && name.endsWith(".btm"));
        assertFalse(files == null || files.length == 0, "Byteman output should be generated");
        List<File> sorted = Arrays.stream(files)
                .sorted(Comparator.comparing(File::getName))
                .collect(Collectors.toList());
        return Files.readString(sorted.get(0).toPath());
    }
}
