package de.burger.forensics.plugin.btmgen.common;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;

/**
 * Build-tool-neutral verification for semantic artifacts generated by Joern.
 */
public final class ForensicsSemanticImportVerifier {

    public void verify(
            boolean joernEnabled,
            Path joernOutputDirectory,
            String disabledConfigurationHint,
            String semanticAnalysisCommand
    ) {
        Objects.requireNonNull(joernOutputDirectory, "joernOutputDirectory");
        Objects.requireNonNull(disabledConfigurationHint, "disabledConfigurationHint");
        Objects.requireNonNull(semanticAnalysisCommand, "semanticAnalysisCommand");
        if (!joernEnabled) {
            throw new ForensicsSemanticAnalysisException(
                    "Joern semantic import is disabled. Set " + disabledConfigurationHint + " to run it.");
        }
        Path callgraph = joernOutputDirectory.resolve("callgraph.json");
        if (!Files.isRegularFile(callgraph)) {
            throw new ForensicsSemanticAnalysisException(
                    "Joern semantic artifacts are missing. Run " + semanticAnalysisCommand + " first.");
        }
    }
}
