[versions]
junit    = "5.13.4"
archunit = "1.4.1"
junit-platform = "1.11.3"
assertj  = "3.27.7"
javaparser = "3.27.1"
aspectj  = "1.9.24"
bytebuddy = "1.18.2"
slf4j    = "2.0.17"
mockito = "5.13.0"
byteman = "4.0.26"
jakarta-annotation = "2.1.1"
sonar_cloud = "6.3.1.5724"
jacoco = "0.8.13"
lombok = "1.18.42"
freefair-lombok = "9.1.0"

# Gradle plugins
#gradle-plugin-publish = "2.0.0"
#nexus-publish         = "2.0.0"

[plugins]
#gradle-plugin-publish   = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
#nexus-publish           = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
sonar_qube_gradle_plugin = { id = "org.sonarqube", version.ref ="sonar_cloud"}
freefair_lombok_plugin   = { id = "io.freefair.lombok", version.ref = "freefair-lombok" }

[libraries]

# JavaParser
javaparser-symbol-solver-core = { module = "com.github.javaparser:javaparser-symbol-solver-core", version.ref = "javaparser" }

# AspectJ
aspectj-rt     = { module = "org.aspectj:aspectjrt",     version.ref = "aspectj" }
aspectj-weaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectj" }

# Logging
slf4j-api       = { module = "org.slf4j:slf4j-api",        version.ref = "slf4j" }
#slf4j-simple    = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
#jul-to-slf4j    = { module = "org.slf4j:jul-to-slf4j",     version.ref = "slf4j" }
#jcl-over-slf4j  = { module = "org.slf4j:jcl-over-slf4j",   version.ref = "slf4j" }

# Testing (JUnit 5 via BOM + Jupiter)
# BOM
junit-bom               = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter           = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-api       = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine    = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
archunit-junit          = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit"}

# BOM liefert die Versionen für alle Mockito-Module
mockito-bom           = { module = "org.mockito:mockito-bom", version.ref = "mockito" }
mockito-core          = { module = "org.mockito:mockito-core" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter" }
#mockito-inline       = { module = "org.mockito:mockito-inline" }

# ByteBuddy agent
byte-buddy-agent = { module = "net.bytebuddy:byte-buddy-agent", version.ref = "bytebuddy" }

# Assertions
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
byteman = { module = "org.jboss.byteman:byteman", version.ref = "byteman" }
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }

# Boilerplade Code
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
