package de.burger.forensics.plugin.btmgen.writer;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.time.Clock;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Objects;

/**
 * Writes a single .btm file with a small header and rule blocks.
 */
public final class BtmFileWriter {

    private final Path output;
    private final Clock clock; // may be null if ctor without a clock is used

    /** Preferred constructor keeping time explicit. */
    public BtmFileWriter(Clock clock, Path output) {
        this.clock = Objects.requireNonNull(clock, "clock");
        this.output = Objects.requireNonNull(output, "output");
    }

    /** Backward-compatible constructor (uses a system clock). */
    public BtmFileWriter(Path output) {
        this(Clock.systemDefaultZone(), output);
    }

    public void write(List<String> rules) {
        try {
            Files.createDirectories(output.getParent());
            try (var writer = Files.newBufferedWriter(output, StandardCharsets.UTF_8,
                    StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING)) {
                writer.write("# Generated Byteman rules");
                writer.write(System.lineSeparator());
                writer.write("# Timestamp: " + ZonedDateTime.now(clock).format(DateTimeFormatter.ISO_OFFSET_DATE_TIME));
                writer.write(System.lineSeparator());
                writer.write(System.lineSeparator());
            }
            appendRules(output, rules);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private void appendRules(Path out, List<String> rules) throws IOException {
        if (rules == null || rules.isEmpty()) return;
        try (var writer = Files.newBufferedWriter(out, StandardCharsets.UTF_8, StandardOpenOption.APPEND)) {
            for (String rule : rules) {
                writer.write(rule);
                writer.write(System.lineSeparator());
                writer.write(System.lineSeparator());
            }
        }
    }
}
