package de.burger.forensics.plugin

import org.gradle.testkit.runner.GradleRunner
import org.gradle.testkit.runner.TaskOutcome
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.io.File
import java.nio.file.Files

class BtmGenPluginFunctionalTest {

    @Test
    fun pluginRegistersTask_and_defaultHeaderHasNoTimestamp() {
        val projectDir = Files.createTempDirectory("btmgen-plugin-test1").toFile().apply { deleteOnExit() }
        writeSettings(projectDir)
        writeBuildScript(projectDir, includeTimestamp = false)
        writeMinimalSource(projectDir)

        val result = GradleRunner.create()
            .withProjectDir(projectDir)
            .withArguments("generateBtmRules", "--stacktrace")
            .withPluginClasspath()
            .build()

        val task = result.task(":generateBtmRules")
        assertEquals(TaskOutcome.SUCCESS, task?.outcome, "generateBtmRules should succeed")

        val outputDir = File(projectDir, "build/forensics")
        val outputFiles = outputDir.listFiles { _, name ->
            name.startsWith("tracing-") && name.endsWith(".btm")
        }?.sortedBy { it.name }
        assertTrue(!outputFiles.isNullOrEmpty(), "Byteman output should be generated")

        val output = outputFiles!!.first().readText()
        assertTrue(output.lines().first().contains("Generated by de.burger.forensics.btmgen"),
            "Default header should not contain timestamp")
        assertTrue(!output.contains("Generated at"), "Timestamp should be omitted by default for cacheability")
    }

    @Test
    fun pluginWiresExtension_includeTimestampTrue_addsTimestamp() {
        val projectDir = Files.createTempDirectory("btmgen-plugin-test2").toFile().apply { deleteOnExit() }
        writeSettings(projectDir)
        writeBuildScript(projectDir, includeTimestamp = true)
        writeMinimalSource(projectDir)

        val result = GradleRunner.create()
            .withProjectDir(projectDir)
            .withArguments("generateBtmRules", "--stacktrace")
            .withPluginClasspath()
            .build()

        val task = result.task(":generateBtmRules")
        assertEquals(TaskOutcome.SUCCESS, task?.outcome, "generateBtmRules should succeed")

        val outputDir = File(projectDir, "build/forensics")
        val outputFiles = outputDir.listFiles { _, name ->
            name.startsWith("tracing-") && name.endsWith(".btm")
        }?.sortedBy { it.name }
        assertTrue(!outputFiles.isNullOrEmpty(), "Byteman output should be generated")

        val output = outputFiles!!.first().readText()
        assertTrue(output.lines().first().contains("Generated at"),
            "Header should include timestamp when includeTimestamp=true")
    }

    private fun writeSettings(projectDir: File) {
        File(projectDir, "settings.gradle.kts").writeText(
            "rootProject.name = \"sample-project\"\n"
        )
    }

    private fun writeBuildScript(projectDir: File, includeTimestamp: Boolean) {
        File(projectDir, "build.gradle.kts").writeText(
            """
            plugins {
                id("de.burger.forensics.btmgen")
            }

            repositories { mavenCentral() }

            forensicsBtmGen {
                pkgPrefix.set("")
                includeTimestamp.set($includeTimestamp)
            }
            """.trimIndent()
        )
    }

    private fun writeMinimalSource(projectDir: File) {
        val sourceDir = File(projectDir, "src/main/kotlin")
        sourceDir.mkdirs()
        File(sourceDir, "TopLevel.kt").writeText(
            """
            fun hello(name: String): String {
                return "Hello, ${'$'}name"
            }
            """.trimIndent()
        )
    }
}
