package de.burger.forensics.plugin.btmgen.writer;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class BtmFileWriterTest {

    @TempDir
    Path tempDir;

    @Test
    void writeUsesDeterministicHeaderByDefault() throws IOException {
        Path output = tempDir.resolve("rules.btm");

        new BtmFileWriter(Clock.fixed(Instant.parse("2024-02-29T10:15:30Z"), ZoneOffset.UTC), output).write(List.of());

        List<String> lines = Files.readAllLines(output);
        assertEquals(List.of("# Generated Byteman rules", ""), lines);
    }

    @Test
    void writeCanIncludeTimestampHeaderWhenEnabled() throws IOException {
        Path output = tempDir.resolve("rules-with-time.btm");

        new BtmFileWriter(
                Clock.fixed(Instant.parse("2024-02-29T10:15:30Z"), ZoneOffset.UTC),
                output,
                true
        ).write(List.of());

        List<String> lines = Files.readAllLines(output);
        assertEquals("# Generated Byteman rules", lines.get(0));
        assertEquals("# Timestamp: 2024-02-29T10:15:30Z", lines.get(1));
        assertEquals("", lines.get(2));
    }

    @Test
    void writeAddsRuleBlocksWithSpacing() throws IOException {
        Path output = tempDir.resolve("ruleSpacing/rules.btm");

        new BtmFileWriter(Clock.systemUTC(), output).write(List.of("RULE alpha", "RULE beta"));

        List<String> lines = Files.readAllLines(output);
        assertEquals("RULE alpha", lines.get(2));
        assertEquals("", lines.get(3));
        assertEquals("RULE beta", lines.get(4));
        assertEquals("", lines.get(5));
    }

    @Test
    void writeWrapsIoExceptionsInUncheckedIOException() throws IOException {
        Path blockingParent = tempDir.resolve("blockingParent");
        Files.createFile(blockingParent);
        Path output = blockingParent.resolve("cannotCreate.btm");
        BtmFileWriter writer = new BtmFileWriter(Clock.systemUTC(), output);
        List<String> rules = List.of("RULE X");

        assertThrows(UncheckedIOException.class, () -> writer.write(rules));
    }
}
