package de.burger.forensics.plugin.io;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.Clock;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Writes generated Byteman rules to disk including optional metadata headers.
 */
public final class BtmFileWriter {

    private final Clock clock;

    public BtmFileWriter(Clock clock) {
        this.clock = Objects.requireNonNull(clock, "clock");
    }

    public void write(Path output,
                      boolean includeTimestamp,
                      String helperFqcn,
                      List<String> rules) {
        Objects.requireNonNull(output, "output");
        Objects.requireNonNull(helperFqcn, "helperFqcn");
        Objects.requireNonNull(rules, "rules");

        try {
            Path parent = output.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            List<String> header = createHeader(includeTimestamp, helperFqcn, rules.size());
            Files.write(output, header, StandardCharsets.UTF_8);
            appendRules(output, rules);
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to write generated rules", e);
        }
    }

    private List<String> createHeader(boolean includeTimestamp, String helperFqcn, int ruleCount) {
        List<String> lines = new ArrayList<>();
        if (includeTimestamp) {
            lines.add("# Generated at " + DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(ZonedDateTime.now(clock)));
        } else {
            lines.add("# Generated rules");
        }
        lines.add("# Helper: " + helperFqcn);
        if (ruleCount > 0) {
            lines.add("# Rule count: " + ruleCount);
        }
        lines.add("");
        return lines;
    }

    private void appendRules(Path output, List<String> rules) throws IOException {
        if (rules.isEmpty()) {
            return;
        }
        try (var writer = Files.newBufferedWriter(output, StandardCharsets.UTF_8, StandardOpenOption.APPEND)) {
            for (String rule : rules) {
                writer.write(rule);
                writer.write(System.lineSeparator());
                writer.write(System.lineSeparator());
            }
        }
    }
}
