package de.burger.forensics.plugin.btmgen.gradle;

import de.burger.forensics.adapters.javaparser.JavaParserScanner;
import de.burger.forensics.application.service.GenerateRulesUseCase;
import de.burger.forensics.application.service.GenerationRequest;
import de.burger.forensics.application.service.RuleGenerationResult;
import de.burger.forensics.domain.strategy.DefaultStrategyFactory;
import de.burger.forensics.plugin.adapters.GradleLogAdapter;
import de.burger.forensics.plugin.adapters.SystemClockAdapter;
import de.burger.forensics.plugin.btmgen.internal.BytemanRuleRenderAdapter;
import de.burger.forensics.plugin.btmgen.render.BytemanRuleRenderer;
import de.burger.forensics.plugin.btmgen.render.api.RuleParams;
import de.burger.forensics.plugin.btmgen.render.spi.StrategyRegistries;
import de.burger.forensics.plugin.btmgen.render.spi.StrategyRegistry;
import de.burger.forensics.plugin.btmgen.writer.BtmFileWriter;
import org.gradle.api.DefaultTask;
import org.gradle.api.GradleException;
import org.gradle.api.Project;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.file.FileTree;
import org.gradle.api.file.ProjectLayout;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.model.ObjectFactory;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.*;
import org.gradle.api.tasks.Optional;
import org.gradle.api.tasks.SourceSet;
import org.gradle.api.tasks.SourceSetContainer;
import org.gradle.work.DisableCachingByDefault;
import org.jetbrains.annotations.NotNull;

import javax.inject.Inject;
import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Clock;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Scans Java sources and renders Byteman rules using {@link GenerateRulesUseCase}.
 */
@DisableCachingByDefault(because = "The generated Byteman file includes a timestamp header and is not reproducible across executions.")
public abstract class GenerateBtmTask extends DefaultTask {
    private StrategyRegistry registry = StrategyRegistries.defaultRegistry();

    // ---- Configurable inputs ----
    @Internal
    public abstract DirectoryProperty getSourceRoot();

    @Internal
    public abstract ConfigurableFileCollection getSourceRoots();

    @Internal
    public abstract ConfigurableFileCollection getCurrentProjectSourceSetRoots();

    @Internal
    public abstract ConfigurableFileCollection getSubprojectSourceSetRoots();

    @InputFiles
    @Optional
    @PathSensitive(PathSensitivity.RELATIVE)
    public FileTree getSourceFiles() {
        applyDefaultConventions();
        ConfigurableFileCollection sourceFiles = getObjectFactory().fileCollection();
        resolveSourceRoots().forEach(root -> sourceFiles.from(root.toFile()));
        return sourceFiles.getAsFileTree().matching(patterns -> patterns.include("**/*.java"));
    }

    @OutputFile
    @Optional
    public abstract RegularFileProperty getOutputFile();

    @Internal
    public abstract DirectoryProperty getOutputDir();

    /** Optional: render exactly one template with given class/method instead of scanning. */
    @Input @Optional public abstract Property<@NotNull String> getTemplateId();
    @Input @Optional public abstract Property<@NotNull String> getClassName();
    @Input @Optional public abstract Property<@NotNull String> getMethodName();
    @Input @Optional public abstract Property<@NotNull String> getMethodDesc();
    @Input @Optional public abstract Property<@NotNull Boolean> getIncludeEntryExit();
    @Input @Optional public abstract Property<@NotNull Integer>  getMinBranchesPerMethod();
    @Input @Optional public abstract Property<@NotNull String>  getHelperFqn();
    @Input @Optional public abstract Property<@NotNull String>  getIncludes();
    @Input @Optional public abstract Property<@NotNull Boolean> getScanSubprojects();
    @Input @Optional public abstract Property<@NotNull String> getRegistryFingerprint();

    /** Injected via plugin apply() */
    public void setExtension(BtmGenExtension ext) {
        applyDefaultConventions();

        getSourceRoot().set(ext.getSourceRoot().get());
        getSourceRoots().setFrom(ext.getSourceRoots());
        File outputFile = ext.getOutputFile().get();
        getOutputFile().fileValue(outputFile);
        if (outputFile.getParentFile() != null) {
            getOutputDir().fileValue(outputFile.getParentFile());
        }
        getHelperFqn().convention(ext.getHelperFqn());
        getIncludes().convention(ext.getIncludes());
        getMinBranchesPerMethod().convention(ext.getMinBranchesPerMethod());
        getScanSubprojects().convention(ext.getScanSubprojects());
        registry = ext.getRegistry() == null ? StrategyRegistries.defaultRegistry() : ext.getRegistry();
        getRegistryFingerprint().set(registryFingerprint(registry));
        configureSourceSetRoots();
    }

    @TaskAction
    public void generate() {
        applyDefaultConventions();
        final Path outFile = getOutputFile().get().getAsFile().toPath();
        BytemanRuleRenderer renderer = BytemanRuleRenderer.of(activeRegistry());

        createOutputDirectory(outFile);

        List<String> allRules = new ArrayList<>();

        if (hasMinimalInputs()) {
            RuleParams params = new RuleParams(
                    templateIdOrDefault(),
                    getClassName().get(),
                    getMethodName().get(),
                    getMethodDesc().getOrNull(),
                    getClassName().get() + "#" + getMethodName().get(),
                    null,
                    null,
                    resolveHelperFqn()
            );
            allRules.add(renderer.render(templateIdOrDefault(), params));
        } else {
            GenerateRulesUseCase useCase = new GenerateRulesUseCase(
                new JavaParserScanner(),
                new BytemanRuleRenderAdapter(renderer),
                new SystemClockAdapter(),
                new GradleLogAdapter(getLogger()),
                new DefaultStrategyFactory()
            );
            for (Path srcRoot : resolveSourceRoots()) {
                getLogger().lifecycle("Scanning sources in {}", srcRoot.toAbsolutePath());
                GenerationRequest request = new GenerationRequest(
                    srcRoot,
                    resolveHelperFqn(),
                    false,
                    includeEntryExit(),
                    packagePrefixes(),
                    minBranches(),
                    Collections.emptyList()
                );
                RuleGenerationResult result = useCase.generate(request);
                allRules.addAll(result.renderedRules());
            }
        }

        List<String> uniqueRules = new ArrayList<>(new LinkedHashSet<>(allRules));
        List<String> dedupedRuleNames = dedupeRuleHeaders(uniqueRules);
        writeRules(outFile, dedupedRuleNames);

        getLogger().lifecycle("Generated {} rules -> {}", dedupedRuleNames.size(), outFile.toAbsolutePath());
    }

    @Inject
    protected abstract ObjectFactory getObjectFactory();

    @Inject
    protected abstract ProjectLayout getProjectLayout();

    private void applyDefaultConventions() {
        ProjectLayout layout = getProjectLayout();
        if (!getSourceRoot().isPresent()) {
            getSourceRoot().convention(layout.getProjectDirectory().dir("src/main/java"));
        }
        if (!getOutputFile().isPresent()) {
            getOutputFile().convention(layout.getBuildDirectory().file("forensics/forensics.btm"));
        }
        if (!getOutputDir().isPresent()) {
            getOutputDir().convention(layout.getBuildDirectory().dir("forensics"));
        }
        if (!getIncludeEntryExit().isPresent()) {
            getIncludeEntryExit().convention(true);
        }
        if (!getMinBranchesPerMethod().isPresent()) {
            getMinBranchesPerMethod().convention(2);
        }
        if (!getHelperFqn().isPresent()) {
            getHelperFqn().convention(RuleParams.DEFAULT_HELPER_FQN);
        }
        if (!getIncludes().isPresent()) {
            getIncludes().convention("");
        }
        if (!getScanSubprojects().isPresent()) {
            getScanSubprojects().convention(false);
        }
        if (!getRegistryFingerprint().isPresent()) {
            getRegistryFingerprint().convention(registryFingerprint(registry));
        }
    }

    private void configureSourceSetRoots() {
        getCurrentProjectSourceSetRoots().setFrom(mainSourceSetRoots(getProject()));
        List<File> subprojectRoots = getProject().getSubprojects().stream()
                .sorted(Comparator.comparing(Project::getPath))
                .flatMap(subproject -> mainSourceSetRoots(subproject).stream())
                .toList();
        getSubprojectSourceSetRoots().setFrom(subprojectRoots);
    }

    private boolean hasMinimalInputs() {
        return getTemplateId().isPresent() && getClassName().isPresent() && getMethodName().isPresent();
    }

    private String templateIdOrDefault() {
        String id = getTemplateId().getOrElse("METHOD_ENTER");
        return id.isBlank() ? "METHOD_ENTER" : id;
    }

    private String resolveHelperFqn() {
        String helper = getHelperFqn().getOrElse(RuleParams.DEFAULT_HELPER_FQN);
        return helper.isBlank() ? RuleParams.DEFAULT_HELPER_FQN : helper;
    }

    private boolean includeEntryExit() {
        return getIncludeEntryExit().getOrElse(true);
    }

    private int minBranches() {
        return getMinBranchesPerMethod().getOrElse(2);
    }

    private List<Path> resolveSourceRoots() {
        applyDefaultConventions();
        LinkedHashSet<Path> roots = new LinkedHashSet<>();
        addSourceRoot(roots, getSourceRoot().getOrNull() == null ? null : getSourceRoot().get().getAsFile());
        sortedFiles(getSourceRoots().getFiles()).forEach(file -> addSourceRoot(roots, file));
        sortedFiles(getCurrentProjectSourceSetRoots().getFiles()).forEach(file -> addSourceRoot(roots, file));
        if (getScanSubprojects().getOrElse(false)) {
            sortedFiles(getSubprojectSourceSetRoots().getFiles()).forEach(file -> addSourceRoot(roots, file));
        }
        return roots.stream()
                .filter(GenerateBtmTask::isExistingSourceLocation)
                .toList();
    }

    private List<String> packagePrefixes() {
        String includes = getIncludes().getOrElse("");
        if (includes.isBlank()) {
            return Collections.emptyList();
        }
        return Arrays.stream(includes.split(","))
                .map(String::trim)
                .filter(s -> !s.isEmpty())
                .toList();
    }

    private List<String> dedupeRuleHeaders(List<String> rules) {
        Map<String, Integer> seen = new HashMap<>();
        List<String> out = new ArrayList<>(rules.size());
        for (String rule : rules) {
            RuleHeader header = findRuleHeader(rule);
            String rewrittenRule = rule;
            if (header != null) {
                String originalName = header.name();
                int index = seen.merge(originalName, 1, Integer::sum);
                if (index > 1) {
                    String replacement = header.prefix() + originalName + "_" + index;
                    rewrittenRule = rule.substring(0, header.startIndex()) + replacement + rule.substring(header.endIndex());
                }
            }
            out.add(rewrittenRule);
        }
        return out;
    }

    private static RuleHeader findRuleHeader(String rule) {
        int lineStart = 0;
        while (lineStart < rule.length()) {
            int lineEnd = findLineEnd(rule, lineStart);
            RuleHeader header = parseRuleHeader(rule, lineStart, lineEnd);
            if (header != null) {
                return header;
            }
            lineStart = skipLineBreak(rule, lineEnd);
        }
        return null;
    }

    private static RuleHeader parseRuleHeader(String rule, int lineStart, int lineEnd) {
        int contentStart = skipInlineWhitespace(rule, lineStart, lineEnd);
        if (!matchesKeyword(rule, contentStart, lineEnd)) {
            return null;
        }

        int afterKeyword = contentStart + "RULE".length();
        if (afterKeyword >= lineEnd || !Character.isWhitespace(rule.charAt(afterKeyword))) {
            return null;
        }

        int nameStart = skipInlineWhitespace(rule, afterKeyword, lineEnd);
        if (nameStart >= lineEnd) {
            return null;
        }

        int nameEnd = trimInlineWhitespace(rule, nameStart, lineEnd);
        String prefix = rule.substring(lineStart, nameStart);
        String name = rule.substring(nameStart, nameEnd);
        return new RuleHeader(lineStart, lineEnd, prefix, name);
    }

    private static boolean matchesKeyword(String rule, int start, int lineEnd) {
        int keywordEnd = start + "RULE".length();
        return keywordEnd <= lineEnd && rule.regionMatches(start, "RULE", 0, "RULE".length());
    }

    private static int skipInlineWhitespace(String rule, int start, int end) {
        int cursor = start;
        while (cursor < end && Character.isWhitespace(rule.charAt(cursor))) {
            cursor++;
        }
        return cursor;
    }

    private static int trimInlineWhitespace(String rule, int start, int end) {
        int cursor = end;
        while (cursor > start && Character.isWhitespace(rule.charAt(cursor - 1))) {
            cursor--;
        }
        return cursor;
    }

    private static int findLineEnd(String rule, int lineStart) {
        int cursor = lineStart;
        while (cursor < rule.length()) {
            char current = rule.charAt(cursor);
            if (current == '\n' || current == '\r') {
                return cursor;
            }
            cursor++;
        }
        return rule.length();
    }

    private static int skipLineBreak(String rule, int lineEnd) {
        if (lineEnd >= rule.length()) {
            return rule.length();
        }
        if (rule.charAt(lineEnd) == '\r' && lineEnd + 1 < rule.length() && rule.charAt(lineEnd + 1) == '\n') {
            return lineEnd + 2;
        }
        return lineEnd + 1;
    }

    private void writeRules(Path outFile, List<String> rules) {
        try {
            createWriter(outFile).write(rules);
        } catch (UncheckedIOException e) {
            throw new GradleException("Failed writing BTM file " + outFile, e);
        }
    }

    private void createOutputDirectory(Path outFile) {
        Path parent = outFile.getParent();
        if (parent == null) {
            return;
        }
        try {
            Files.createDirectories(parent);
        } catch (IOException e) {
            throw new GradleException("Failed to create output directory for " + outFile, e);
        }
    }

    private static BtmFileWriter createWriter(Path outFile) {
        try {
            return new BtmFileWriter(Clock.systemDefaultZone(), outFile);
        } catch (NoSuchMethodError | NoClassDefFoundError e) {
            return new BtmFileWriter(outFile);
        }
    }

    private static Set<File> mainSourceSetRoots(Project candidate) {
        SourceSetContainer sourceSets = candidate.getExtensions().findByType(SourceSetContainer.class);
        if (sourceSets == null) {
            return Set.of();
        }

        SourceSet mainSourceSet = sourceSets.findByName(SourceSet.MAIN_SOURCE_SET_NAME);
        if (mainSourceSet == null) {
            return Set.of();
        }

        return mainSourceSet.getAllJava().getSrcDirs();
    }

    private static List<File> sortedFiles(Set<File> files) {
        return files.stream()
                .sorted(Comparator.comparing(file -> file.toPath().toAbsolutePath().normalize().toString()))
                .toList();
    }

    private static void addSourceRoot(Set<Path> roots, File root) {
        if (root == null) {
            return;
        }
        roots.add(root.toPath().toAbsolutePath().normalize());
    }

    private static boolean isExistingSourceLocation(Path path) {
        return Files.exists(path) && (Files.isDirectory(path) || Files.isRegularFile(path));
    }

    private static String registryFingerprint(StrategyRegistry candidateRegistry) {
        return candidateRegistry.ids().stream()
                .sorted()
                .map(id -> id + "=" + candidateRegistry.find(id)
                        .map(strategy -> strategy.getClass().getName())
                        .orElse("missing"))
                .reduce((left, right) -> left + "," + right)
                .orElse("");
    }

    private StrategyRegistry activeRegistry() {
        if (registry != null) {
            return registry;
        }

        StrategyRegistry defaultRegistry = StrategyRegistries.defaultRegistry();
        String defaultFingerprint = registryFingerprint(defaultRegistry);
        String configuredFingerprint = getRegistryFingerprint().getOrElse(defaultFingerprint);
        if (!configuredFingerprint.equals(defaultFingerprint)) {
            throw new GradleException(
                    "Custom StrategyRegistry instances are not supported when the configuration cache restores this task. " +
                    "Disable the configuration cache for this build or use the built-in strategy registry."
            );
        }
        registry = defaultRegistry;
        return registry;
    }

    private record RuleHeader(int startIndex, int endIndex, String prefix, String name) { }
}
