package de.burger.forensics.plugin.btmgen.gradle;

import org.gradle.api.DefaultTask;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.Directory;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.file.ProjectLayout;
import org.gradle.api.logging.Logger;
import org.gradle.api.provider.ListProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.*;

import javax.inject.Inject;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.List;

public abstract class GenerateBtmTask extends DefaultTask {

    @InputFiles
    public abstract ConfigurableFileCollection getSourceFiles();

    @Input public abstract Property<Boolean> getIncludeJava();
    @Input public abstract Property<Boolean> getUseAstScanner();
    @Input public abstract Property<String>  getHelperFqn();
    @Input public abstract Property<Boolean> getEntryExit();
    @Input public abstract Property<Integer> getMinBranchesPerMethod();
    @Input public abstract Property<Boolean> getLogToFile();
    @Input public abstract Property<String>  getLogFilePath();

    @OutputDirectory
    public abstract DirectoryProperty getOutputDir();

    @Inject
    public abstract ProjectLayout getLayout();

    @TaskAction
    public void generate() throws Exception {
        Logger log = getLogger();
        Directory out = getOutputDir().get();
        File outDir = out.getAsFile();
        outDir.mkdirs();

        // Very small PoC writer: generate one .btm per shard (here: single file)
        File file = new File(outDir, "tracing0001-00001.btm");
        String text = """
                # Generated by GenerateBtmTask
                # Helper: %s

                RULE Trace Main.main entry
                CLASS de.burger.it.Main
                METHOD main(java.lang.String[])
                AT ENTRY
                IF TRUE
                DO traceln("ENTER Main.main")
                ENDRULE

                RULE Trace Main.main exit
                CLASS de.burger.it.Main
                METHOD main(java.lang.String[])
                AT EXIT
                IF TRUE
                DO traceln("EXIT Main.main")
                ENDRULE
                """.formatted(getHelperFqn().get());
        Files.writeString(file.toPath(), text, StandardCharsets.UTF_8);

        log.lifecycle("generateBtmRules: wrote 1 .btm file to " + outDir.getAbsolutePath());
    }
}
