package de.burger.forensics.plugin.btmgen.gradle;

import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.TaskOutcome;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class BtmGenPluginFunctionalTest {
    private static final String TIMESTAMP_CACHE_REASON =
            "Timestamp header is enabled and makes generated .btm output non-deterministic.";

    @Test
    void generateBtmRulesWorksInASimpleJavaProject(@TempDir Path tempDir) throws IOException {
        writeSimpleSettings(tempDir);
        Files.writeString(tempDir.resolve("build.gradle.kts"), simpleBuildScript());
        writeJavaSource(
            tempDir.resolve("src/main/java"),
            "com.example.simple",
            "SimpleService",
            "simpleMethod"
        );

        BuildResult result = runGradle(tempDir, ":generateBtmRules");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(result, ":generateBtmRules"));
        String output = Files.readString(tempDir.resolve("build/forensics/forensics.btm"));
        assertTrue(output.contains("com.example.simple.SimpleService#simpleMethod"));
    }

    @Test
    void generateBtmRulesReusesTheConfigurationCache(@TempDir Path tempDir) throws IOException {
        writeSimpleSettings(tempDir);
        Files.writeString(tempDir.resolve("build.gradle.kts"), simpleBuildScript());
        writeJavaSource(
            tempDir.resolve("src/main/java"),
            "com.example.cache",
            "CacheService",
            "cacheMethod"
        );

        BuildResult firstRun = runGradle(tempDir, "--configuration-cache", ":generateBtmRules");
        BuildResult secondRun = runGradle(tempDir, "--configuration-cache", ":generateBtmRules");

        TaskOutcome firstOutcome = taskOutcome(firstRun, ":generateBtmRules");
        assertEquals(TaskOutcome.SUCCESS, firstOutcome);
        assertTrue(firstRun.getOutput().contains("Configuration cache entry stored."));
        assertEquals(TaskOutcome.UP_TO_DATE, taskOutcome(secondRun, ":generateBtmRules"));
        assertTrue(secondRun.getOutput().contains("Configuration cache entry reused."));
    }

    @Test
    void generateBtmRulesDoesNotWriteTimestampHeaderByDefault(@TempDir Path tempDir) throws IOException {
        writeSimpleSettings(tempDir);
        Files.writeString(tempDir.resolve("build.gradle.kts"), simpleBuildScript());
        writeJavaSource(
            tempDir.resolve("src/main/java"),
            "com.example.deterministic",
            "DeterministicService",
            "deterministicMethod"
        );

        BuildResult result = runGradle(tempDir, ":generateBtmRules");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(result, ":generateBtmRules"));
        List<String> lines = Files.readAllLines(tempDir.resolve("build/forensics/forensics.btm"));
        assertEquals("# Generated Byteman rules", lines.get(0));
        assertFalse(lines.stream().anyMatch(line -> line.startsWith("# Timestamp:")));
    }

    @Test
    void generateBtmRulesCanBeLoadedFromBuildCacheAcrossCleanBuilds(@TempDir Path tempDir) throws IOException {
        writeSimpleSettings(tempDir);
        Files.writeString(tempDir.resolve("build.gradle.kts"), simpleBuildScript());
        writeJavaSource(
            tempDir.resolve("src/main/java"),
            "com.example.cacheable",
            "CacheableService",
            "cacheableMethod"
        );

        BuildResult firstRun = runGradle(tempDir, "--build-cache", ":generateBtmRules");
        BuildResult secondRun = runGradle(tempDir, "--build-cache", "clean", ":generateBtmRules");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(firstRun, ":generateBtmRules"));
        assertEquals(TaskOutcome.FROM_CACHE, taskOutcome(secondRun, ":generateBtmRules"));
    }

    @Test
    void generateBtmRulesWithTimestampHeaderDoesNotUseBuildCache(@TempDir Path tempDir) throws IOException {
        writeSimpleSettings(tempDir);
        Files.writeString(tempDir.resolve("build.gradle.kts"), simpleBuildScript("""
                btmGen {
                    includeTimestampHeader.set(true)
                }
                """));
        writeJavaSource(
            tempDir.resolve("src/main/java"),
            "com.example.timestamped",
            "TimestampedService",
            "timestampedMethod"
        );

        BuildResult firstRun = runGradle(tempDir, "--build-cache", "--info", ":generateBtmRules");
        BuildResult secondRun = runGradle(tempDir, "--build-cache", "--info", "clean", ":generateBtmRules");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(firstRun, ":generateBtmRules"));
        assertEquals(TaskOutcome.SUCCESS, taskOutcome(secondRun, ":generateBtmRules"));
        assertTrue(secondRun.getOutput().contains(TIMESTAMP_CACHE_REASON));

        List<String> lines = Files.readAllLines(tempDir.resolve("build/forensics/forensics.btm"));
        assertTrue(lines.stream().anyMatch(line -> line.startsWith("# Timestamp:")));
    }

    @Test
    void monorepoModeReusesConfigurationCache(@TempDir Path tempDir) throws IOException {
        writeMonorepoSettings(tempDir, "module-a");
        Files.writeString(tempDir.resolve("build.gradle.kts"), rootBuildScript());
        Files.writeString(tempDir.resolve("module-a/build.gradle.kts"), defaultJavaSubprojectBuildScript());
        writeJavaSource(tempDir.resolve("module-a/src/main/java"), "com.example.configcache", "ConfigCacheService", "cached");

        BuildResult firstRun = runGradle(tempDir, "--configuration-cache", ":generateBtmRules");
        BuildResult secondRun = runGradle(tempDir, "--configuration-cache", ":generateBtmRules");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(firstRun, ":generateBtmRules"));
        assertTrue(firstRun.getOutput().contains("Configuration cache entry stored."));
        assertEquals(TaskOutcome.UP_TO_DATE, taskOutcome(secondRun, ":generateBtmRules"));
        assertTrue(secondRun.getOutput().contains("Configuration cache entry reused."));
    }

    @Test
    void generateBtmRulesIgnoresNonJavaSubprojectsSafely(@TempDir Path tempDir) throws IOException {
        writeMonorepoSettings(tempDir, "module-a", "docs");
        Files.writeString(tempDir.resolve("build.gradle.kts"), rootBuildScript());
        Files.writeString(tempDir.resolve("module-a/build.gradle.kts"), defaultJavaSubprojectBuildScript());
        Files.writeString(tempDir.resolve("docs/build.gradle.kts"), """
                tasks.register("describe") {
                    doLast {
                        println("documentation-only project")
                    }
                }
                """);
        writeJavaSource(tempDir.resolve("module-a/src/main/java"), "com.example.modulea", "ModuleAService", "moduleA");

        BuildResult result = runGradle(tempDir, ":generateBtmRules");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(result, ":generateBtmRules"));
        String output = Files.readString(tempDir.resolve("build/forensics/all-modules.btm"));
        assertTrue(output.contains("com.example.modulea.ModuleAService#moduleA"));
        assertFalse(output.contains("documentation-only project"));
    }

    @Test
    void generateBtmRulesDoesNotFailForEmptyJavaSubprojects(@TempDir Path tempDir) throws IOException {
        writeMonorepoSettings(tempDir, "empty-java");
        Files.writeString(tempDir.resolve("build.gradle.kts"), rootBuildScript());
        Files.writeString(tempDir.resolve("empty-java/build.gradle.kts"), defaultJavaSubprojectBuildScript());

        BuildResult result = runGradle(tempDir, ":generateBtmRules");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(result, ":generateBtmRules"));
        List<String> lines = Files.readAllLines(tempDir.resolve("build/forensics/all-modules.btm"));
        assertEquals(List.of("# Generated Byteman rules", ""), lines);
    }

    @Test
    void runtimeHelperAttachmentIsOrderIndependentForSubprojects(@TempDir Path tempDir) throws IOException {
        writeMonorepoSettings(tempDir, "module-a");
        Files.writeString(tempDir.resolve("build.gradle.kts"), """
                plugins {
                    id("de.burger.forensics.btmgen")
                }

                btmGen {
                    scanSubprojects.set(true)
                }
                """);
        Files.writeString(tempDir.resolve("module-a/build.gradle.kts"), """
                plugins {
                    `java-library`
                }

                tasks.register("printRuntimeClasspath") {
                    doLast {
                        println(configurations.runtimeClasspath.get().files.joinToString("|") { it.absolutePath })
                    }
                }
                """);
        writeJavaSource(tempDir.resolve("module-a/src/main/java"), "com.example.runtime", "RuntimeService", "run");

        BuildResult result = runGradle(tempDir, ":module-a:printRuntimeClasspath");

        assertTrue(result.getOutput().contains("forensics_tracing"));
    }

    @Test
    void generateBtmRulesScansJavaSubprojectsFromTheRootProject(@TempDir Path tempDir) throws IOException {
        writeMonorepoSettings(tempDir, "module-a", "module-b");
        Files.writeString(tempDir.resolve("build.gradle.kts"), rootBuildScript());
        Files.writeString(tempDir.resolve("module-a/build.gradle.kts"), defaultJavaSubprojectBuildScript());
        Files.writeString(tempDir.resolve("module-b/build.gradle.kts"), defaultJavaSubprojectBuildScript());

        writeJavaSource(
            tempDir.resolve("module-a/src/main/java"),
            "com.example.modulea",
            "ModuleAService",
            "moduleA"
        );
        writeJavaSource(
            tempDir.resolve("module-b/src/main/java"),
            "com.example.moduleb",
            "ModuleBService",
            "moduleB"
        );

        BuildResult result = runGradle(tempDir, ":generateBtmRules");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(result, ":generateBtmRules"));
        String output = Files.readString(tempDir.resolve("build/forensics/all-modules.btm"));
        assertTrue(output.contains("com.example.modulea.ModuleAService#moduleA"));
        assertTrue(output.contains("com.example.moduleb.ModuleBService#moduleB"));
        assertFalse(result.getOutput().contains("property 'sourceRoot'"));
        assertFalse(result.getOutput().contains("does not exist"));
    }

    @Test
    void generateBtmRulesScansCustomSubprojectMainSourceSetDirectories(@TempDir Path tempDir) throws IOException {
        writeMonorepoSettings(tempDir, "module-a");
        Files.writeString(tempDir.resolve("build.gradle.kts"), rootBuildScript());
        Files.writeString(tempDir.resolve("module-a/build.gradle.kts"), """
                plugins {
                    `java-library`
                }

                sourceSets {
                    main {
                        java.setSrcDirs(listOf("sources/main/java"))
                    }
                }
                """);

        writeJavaSource(
            tempDir.resolve("module-a/sources/main/java"),
            "com.example.custom",
            "CustomService",
            "customPath"
        );

        BuildResult result = runGradle(tempDir, ":generateBtmRules");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(result, ":generateBtmRules"));
        String output = Files.readString(tempDir.resolve("build/forensics/all-modules.btm"));
        assertTrue(output.contains("com.example.custom.CustomService#customPath"));
    }

    @Test
    void generateBtmRulesBecomesUpToDateAndRerunsAfterSourceChanges(@TempDir Path tempDir) throws IOException {
        writeMonorepoSettings(tempDir, "module-a");
        Files.writeString(tempDir.resolve("build.gradle.kts"), rootBuildScript());
        Files.writeString(tempDir.resolve("module-a/build.gradle.kts"), defaultJavaSubprojectBuildScript());

        Path javaFile = writeJavaSource(
            tempDir.resolve("module-a/src/main/java"),
            "com.example.modulea",
            "ModuleAService",
            "moduleA"
        );

        BuildResult firstRun = runGradle(tempDir, "--build-cache", ":generateBtmRules");
        BuildResult secondRun = runGradle(tempDir, "--build-cache", ":generateBtmRules");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(firstRun, ":generateBtmRules"));
        assertEquals(TaskOutcome.UP_TO_DATE, taskOutcome(secondRun, ":generateBtmRules"));

        Files.writeString(javaFile, """
                package com.example.modulea;
                public class ModuleAService {
                  public int moduleA() {
                    if (true) { }
                    switch (1) { case 1 -> {} }
                    return 1;
                  }

                  public int moduleAUpdated() {
                    if (false) { }
                    switch (2) { case 2 -> {} }
                    return 2;
                  }
                }
                """);

        BuildResult thirdRun = runGradle(tempDir, "--build-cache", ":generateBtmRules");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(thirdRun, ":generateBtmRules"));
        String output = Files.readString(tempDir.resolve("build/forensics/all-modules.btm"));
        assertTrue(output.contains("ModuleAService#moduleAUpdated"));
    }

    @Test
    void generateBtmRulesIgnoresUnrelatedFileChanges(@TempDir Path tempDir) throws IOException {
        writeSimpleSettings(tempDir);
        Files.writeString(tempDir.resolve("build.gradle.kts"), simpleBuildScript());
        writeJavaSource(
            tempDir.resolve("src/main/java"),
            "com.example.unrelated",
            "UnrelatedService",
            "unrelatedMethod"
        );

        BuildResult firstRun = runGradle(tempDir, "--build-cache", ":generateBtmRules");
        Files.writeString(tempDir.resolve("README.md"), "This file must not invalidate Java source scanning.");
        BuildResult secondRun = runGradle(tempDir, "--build-cache", ":generateBtmRules");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(firstRun, ":generateBtmRules"));
        assertEquals(TaskOutcome.UP_TO_DATE, taskOutcome(secondRun, ":generateBtmRules"));
    }

    @Test
    void includedBuildSourcesRequireExplicitSourceRoots(@TempDir Path tempDir) throws IOException {
        Path includedBuildDir = tempDir.resolve("external-lib");
        Files.createDirectories(includedBuildDir);
        Files.writeString(tempDir.resolve("settings.gradle.kts"), """
                rootProject.name = "functional-root"
                includeBuild("external-lib")
                """);
        Files.writeString(includedBuildDir.resolve("settings.gradle.kts"), "rootProject.name = \"external-lib\"");
        Files.writeString(includedBuildDir.resolve("build.gradle.kts"), defaultJavaSubprojectBuildScript());
        writeJavaSource(
            includedBuildDir.resolve("src/main/java"),
            "com.example.external",
            "ExternalService",
            "externalMethod"
        );

        Files.writeString(tempDir.resolve("build.gradle.kts"), rootBuildScript());
        BuildResult autoScanResult = runGradle(tempDir, ":generateBtmRules");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(autoScanResult, ":generateBtmRules"));
        String autoScannedOutput = Files.readString(tempDir.resolve("build/forensics/all-modules.btm"));
        assertFalse(autoScannedOutput.contains("com.example.external.ExternalService#externalMethod"));

        Files.writeString(tempDir.resolve("build.gradle.kts"), rootBuildScript("""
                sourceRoots.from(file("external-lib/src/main/java"))
                """));
        BuildResult explicitRootsResult = runGradle(tempDir, ":generateBtmRules");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(explicitRootsResult, ":generateBtmRules"));
        String explicitRootsOutput = Files.readString(tempDir.resolve("build/forensics/all-modules.btm"));
        assertTrue(explicitRootsOutput.contains("com.example.external.ExternalService#externalMethod"));
    }

    @Test
    void shouldScanExternalMavenStyleSourceRoots(@TempDir Path tempDir) throws IOException {
        Path fakeWildFlyRoot = writeFakeWildFlyLayout(tempDir.resolve("fake-wildfly"));
        Path sidecarProject = tempDir.resolve("wildfly-sidecar");
        Files.createDirectories(sidecarProject);
        writeSimpleSettings(sidecarProject);
        Files.writeString(sidecarProject.resolve("build.gradle.kts"), fakeWildFlySidecarBuildScript());

        BuildResult result = runGradle(sidecarProject, ":generateBtmRules", "-PwildflyRoot=" + fakeWildFlyRoot);

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(result, ":generateBtmRules"));
        Path outputFile = sidecarProject.resolve("build/forensics/wildfly.btm");
        assertTrue(Files.exists(outputFile), "Generated BTM file should exist");
        String output = Files.readString(outputFile);
        assertTrue(output.contains("org.jboss.as.server.ServerService#run"));
        assertTrue(output.contains("org.wildfly.extension.undertow.UndertowService#run"));
        assertFalse(output.contains("org.wildfly.generated.ShouldBeExcluded#run"));
        assertFalse(output.contains("org.wildfly.testsuite.ShouldBeExcludedByDefault#run"));
    }

    @Test
    void shouldIncludeTestsuiteSourceRootsWhenRequested(@TempDir Path tempDir) throws IOException {
        Path fakeWildFlyRoot = writeFakeWildFlyLayout(tempDir.resolve("fake-wildfly"));
        Path sidecarProject = tempDir.resolve("wildfly-sidecar");
        Files.createDirectories(sidecarProject);
        writeSimpleSettings(sidecarProject);
        Files.writeString(sidecarProject.resolve("build.gradle.kts"), fakeWildFlySidecarBuildScript());

        BuildResult result = runGradle(
            sidecarProject,
            ":generateBtmRules",
            "-PwildflyRoot=" + fakeWildFlyRoot,
            "-Pforensics.wildfly.includeTestsuite=true"
        );

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(result, ":generateBtmRules"));
        String output = Files.readString(sidecarProject.resolve("build/forensics/wildfly.btm"));
        assertTrue(output.contains("org.wildfly.testsuite.ShouldBeExcludedByDefault#run"));
        assertFalse(output.contains("org.wildfly.generated.ShouldBeExcluded#run"));
    }

    private static Path writeJavaSource(Path sourceRoot, String packageName, String className, String methodName) throws IOException {
        Path packageDir = sourceRoot.resolve(packageName.replace('.', '/'));
        Files.createDirectories(packageDir);
        Path javaFile = packageDir.resolve(className + ".java");
        Files.writeString(javaFile, """
                package %s;
                public class %s {
                  public int %s() {
                    if (true) { }
                    switch (1) { case 1 -> {} }
                    return 1;
                  }
                }
                """.formatted(packageName, className, methodName));
        return javaFile;
    }

    private static Path writeFakeWildFlyLayout(Path fakeWildFlyRoot) throws IOException {
        Files.createDirectories(fakeWildFlyRoot);
        Files.writeString(fakeWildFlyRoot.resolve("pom.xml"), "<project></project>");
        Files.writeString(fakeWildFlyRoot.resolve("mvnw"), "#!/bin/sh");
        writeJavaSource(
            fakeWildFlyRoot.resolve("server/src/main/java"),
            "org.jboss.as.server",
            "ServerService",
            "run"
        );
        writeJavaSource(
            fakeWildFlyRoot.resolve("undertow/src/main/java"),
            "org.wildfly.extension.undertow",
            "UndertowService",
            "run"
        );
        writeJavaSource(
            fakeWildFlyRoot.resolve("testsuite/integration/src/main/java"),
            "org.wildfly.testsuite",
            "ShouldBeExcludedByDefault",
            "run"
        );
        writeJavaSource(
            fakeWildFlyRoot.resolve("target/generated/src/main/java"),
            "org.wildfly.generated",
            "ShouldBeExcluded",
            "run"
        );
        return fakeWildFlyRoot;
    }

    private static String fakeWildFlySidecarBuildScript() {
        return """
                import org.gradle.api.GradleException
                import java.io.File

                plugins {
                    id("de.burger.forensics.btmgen")
                }

                val excludedDirectoryNames = setOf(".git", ".gradle", ".idea", ".mvn", ".forensics", "target")
                val includeTestsuite = providers.gradleProperty("forensics.wildfly.includeTestsuite")
                    .map { it.toBoolean() }
                    .getOrElse(false)
                val wildFlyRoot = providers.gradleProperty("wildflyRoot")
                    .map { file(it).canonicalFile }
                    .get()

                if (!wildFlyRoot.isDirectory || !wildFlyRoot.resolve("pom.xml").isFile || !wildFlyRoot.resolve("mvnw").isFile) {
                    throw GradleException("Selected directory '${wildFlyRoot.absolutePath}' is not a WildFly checkout or Maven-style WildFly root.")
                }

                fun discoverMavenStyleSourceRoots(root: File): List<File> =
                    root.walkTopDown()
                        .onEnter { directory ->
                            directory == root ||
                                directory.name !in excludedDirectoryNames &&
                                (includeTestsuite || !directory.relativeTo(root).invariantSeparatorsPath.split("/").contains("testsuite"))
                        }
                        .filter { candidate ->
                            candidate.isDirectory && candidate.invariantSeparatorsPath.endsWith("/src/main/java")
                        }
                        .sortedBy { candidate -> candidate.absolutePath }
                        .toList()

                btmGen {
                    scanSubprojects.set(false)
                    sourceRoot.set(file("missing-sidecar-src"))
                    sourceRoots.from(discoverMavenStyleSourceRoots(wildFlyRoot))
                    outputFile.set(layout.buildDirectory.file("forensics/wildfly.btm").get().asFile)
                    minBranchesPerMethod.set(0)
                }
                """;
    }

    private static String rootBuildScript() {
        return rootBuildScript("");
    }

    private static String rootBuildScript(String additionalConfiguration) {
        return """
                plugins {
                    id("de.burger.forensics.btmgen")
                }

                btmGen {
                    scanSubprojects.set(true)
                    outputFile.set(layout.buildDirectory.file("forensics/all-modules.btm").get().asFile)
                    %s
                }
                """.formatted(additionalConfiguration);
    }

    private static String simpleBuildScript() {
        return simpleBuildScript("");
    }

    private static String simpleBuildScript(String additionalConfiguration) {
        return """
                plugins {
                    java
                    id("de.burger.forensics.btmgen")
                }

                java {
                    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
                }
                
                %s
                """.formatted(additionalConfiguration);
    }

    private static String defaultJavaSubprojectBuildScript() {
        return """
                plugins {
                    `java-library`
                }
                """;
    }

    private static void writeMonorepoSettings(Path rootDir, String... modules) throws IOException {
        List<String> includes = new ArrayList<>();
        for (String module : modules) {
            Files.createDirectories(rootDir.resolve(module));
            includes.add("\"" + module + "\"");
        }
        Files.writeString(rootDir.resolve("settings.gradle.kts"), """
                rootProject.name = "functional-root"
                buildCache {
                    local {
                        directory = file("local-build-cache")
                    }
                }
                include(%s)
                """.formatted(String.join(", ", includes)));
    }

    private static void writeSimpleSettings(Path rootDir) throws IOException {
        Files.writeString(rootDir.resolve("settings.gradle.kts"), """
                rootProject.name = "functional-simple"
                buildCache {
                    local {
                        directory = file("local-build-cache")
                    }
                }
                """);
    }

    private static BuildResult runGradle(Path projectDir, String... arguments) {
        List<String> gradleArguments = new ArrayList<>();
        gradleArguments.add("--stacktrace");
        gradleArguments.addAll(List.of(arguments));
        return GradleRunner.create()
            .withProjectDir(projectDir.toFile())
            .withPluginClasspath()
            .withArguments(gradleArguments)
            .build();
    }

    private static TaskOutcome taskOutcome(BuildResult result, String taskPath) {
        assertNotNull(result.task(taskPath), "Expected task " + taskPath + " to be present in the build result");
        return result.task(taskPath).getOutcome();
    }
}
