name: Release

on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Generate Gradle wrapper
        run: gradle wrapper

      - name: Ensure project wrapper is executable
        run: chmod +x forensics-btmgen/gradlew

      - name: Build plugin
        run: ./gradlew :forensics-btmgen:build --console=plain

      - name: Publish to Gradle Plugin Portal
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && secrets.GRADLE_PUBLISH_KEY != '' && secrets.GRADLE_PUBLISH_SECRET != '' }}
        run: ./gradlew :forensics-btmgen:publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

      - name: Publish to Sonatype
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && secrets.OSSRH_USERNAME != '' && secrets.OSSRH_PASSWORD != '' && secrets.SIGNING_KEY != '' && secrets.SIGNING_PASSWORD != '' }}
        run: ./gradlew :forensics-btmgen:publishToSonatype :forensics-btmgen:closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
